source 'https://rubygems.org'
gem 'rails', '4.0.0'
gem 'pg'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'devise'
gem 'haml'
gem 'jbuilder', '~> 1.2'
gem 'bootstrap-sass'
gem 'autoprefixer-rails'
gem 'carrierwave'
group :test do
 gem 'rspec-rails'
 gem 'database_cleaner'
 gem 'factory_girl_rails'
 gem 'capybara'
end
